# Generated by Django 4.1.1 on 2022-09-16 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_student_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roomno',
            new_name='floor',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
