# Generated by Django 4.1.1 on 2022-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_rename_roomno_student_floor_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('hostelname', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.CharField(max_length=100)),
            ],
        ),
    ]
