# Generated by Django 4.1.1 on 2022-09-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_issue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issue',
            new_name='issueee',
        ),
    ]
