# Generated by Django 4.1.1 on 2022-09-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_rename_issue_issueee'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueee',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
